### ISSUE TITLE
Images arent showen on Firefox

### ISSUE THREAD

**Issue by timmmmmb** [card-game-dev/card-game#13]
i heard from 2 different persons that the pictures arent shown on firefox

**Comment by ceoy** [comment]
Interesting, the Bogenschütze is shown, but many other aren't

**Comment by timmmmmb** [comment]
i just tested the game on my macbook with safari and the cards aren't shown there either

**Comment by cravay** [comment]
Sometimes the cards are shown and sometimes they aren't. I have no idea why.

**Comment by cravay** [comment]
Should be fixed now.

**Comment by ceoy** [comment]
working like a charm
